In [1]:
a=10
a

10

In [1]:
a=10
a

10

In [2]:
a=10
b=20
a
b

20

In [3]:
a=10
b=20
a+b

30

In [4]:
a=[20,10,30]
a

[20, 10, 30]

In [5]:
a=[10,"anand",12]
a

[10, 'anand', 12]

In [6]:
a=[10,20,30,40]
a

[10, 20, 30, 40]

In [8]:
import numpy as np
score=np.array(a)
score

array([10, 20, 30, 40])

In [9]:
print(np.max(score))

40


In [10]:
print(np.min(score))

10


In [11]:
d=np.mean(score)
d

np.float64(25.0)

In [12]:
f=np.zeros([3,3])
f

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
''' filling zeros '''
f=np.zeros([5,5])
f

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
g=np.random.rand(5,6)
g

array([[0.1475936 , 0.05052938, 0.51626504, 0.39776887, 0.7069285 ,
        0.72011442],
       [0.00924683, 0.34475075, 0.81383481, 0.64569235, 0.19081053,
        0.0745665 ],
       [0.55961768, 0.97684689, 0.53324666, 0.02960354, 0.07182146,
        0.82303925],
       [0.97151006, 0.63027612, 0.56538879, 0.32518938, 0.2979854 ,
        0.52691685],
       [0.11650923, 0.41259707, 0.44336161, 0.73456584, 0.59729228,
        0.2252324 ]])

In [26]:
a=np.array([1,2,3,4,5,645,78,52,78,1,6,9,8,7,88])
d=np.reshape(a,(3,5))
d

array([[  1,   2,   3,   4,   5],
       [645,  78,  52,  78,   1],
       [  6,   9,   8,   7,  88]])

In [21]:
a=np.array([11,22,33,4,5,6,7,8,9,2,4,6,1,22,3,4])
d=np.reshape(a,(2,8))
d

array([[11, 22, 33,  4,  5,  6,  7,  8],
       [ 9,  2,  4,  6,  1, 22,  3,  4]])

In [24]:
a=np.array([1,2,3,4,5,645,78,52,78,1,6,9,8,7,88])
d=np.reshape(a,(3,5))
d

array([[  1,   2,   3,   4,   5],
       [645,  78,  52,  78,   1],
       [  6,   9,   8,   7,  88]])

In [32]:
''' reshape '''
e=np.array([1,2,3,4,5,6,7,8,9,10])
c=np.reshape(e,(2,5))
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
''' giving value then reshape '''
b=np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
'''slicing   '''
f=np.array([11,1,23,2,3,4,56,7,8,9,15,75,48,])
g=f[0:5]
g

array([11,  1, 23,  2,  3])

In [40]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [41]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a-b

array([-4, -4, -4, -4])

In [42]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a*b

array([ 5, 12, 21, 32])

In [43]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [44]:
''' matrix  formating'''
a=np.array([[1,3,2],[4,5,6]])
b=np.array([[1,5,3],
           [5,6,4],
           [8,2,1]])
c=np.dot(a,b)
c

array([[32, 27, 17],
       [77, 62, 38]])

In [47]:
''' mat.T means transpose in NumPy . it coverts rowa to column'''
mat=np.array([[1,2,3,],
           [4,5,6]])
print(mat.T)

[[1 4]
 [2 5]
 [3 6]]


In [48]:
ad=np.array([9,5,8,6,32,7,14,2,1,])
print(np.sort(ad))

[ 1  2  5  6  7  8  9 14 32]


In [51]:
a=np.array([1,2,3])
b=np.array([8,5,6])
print(np.concatenate((a,b)))

[1 2 3 8 5 6]


In [53]:
pc=np.array([1,2,3,4,4,5,6,9,9,9,9,8,5,8,9])
dc=np.unique(pc)
dc

array([1, 2, 3, 4, 5, 6, 8, 9])

In [54]:
'''creates an n × n identity matrix.
1 on the main diagonal ↘️
0 everywhere else'''
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [63]:
''' np.linspace() creates evenly spaced numbers between a starting value and an ending value'''
hd=np.linspace(1,11,4)
print(hd)

[ 1.          4.33333333  7.66666667 11.        ]


In [1]:
import numpy as np

a = np.array([1,2,3,4,5])
print(np.argmax(a))

4
