In [1]:
''' accessed by index value '''
import numpy as np

a = np.array([1,2,3,4,5])
print(np.argmax(a))

4


In [2]:
print(np.argmin(a))

0


In [3]:
'''np.where() finds the positions (indexes) where a condition is true.'''
print(np.where(a>3))

(array([3, 4]),)


In [4]:
print(np.cumsum(a))

[ 1  3  6 10 15]


In [5]:
r=np.random.randint(1,20,15)
print(r)

[ 1 16 14  8 14 16  9 16 13 10 19 19  3  9 18]


In [6]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(np.corrcoef(a,b))

[[1. 1.]
 [1. 1.]]


In [7]:
a=np.array([1,2,3,4,5])
b=np.array([10,9,8,7,6])
print(np.corrcoef(a,b))

[[ 1. -1.]
 [-1.  1.]]


In [8]:
a=np.array([1,2,3,4,5])
b=np.array([60,71,88,9,10])
print(np.corrcoef(a,b))

[[ 1.         -0.70788944]
 [-0.70788944  1.        ]]


In [9]:
a=np.array([1,2,3,4,5])
np.save("ad.npy",a)
print(np.load("ad.npy"))

[1 2 3 4 5]
